console.log(Math.pow(2,5));
console.log(Math.round(2.5));
console.log(Math.ceil(2.5));
console.log(Math.floor(2.5));
console.log(Math.abs(-2.5));
console.log(Math.max(1,4,6));
console.log(Math.min())
console.log()
console.log()
console.log()